- hosts: 172.31.38.27
  become: yes
  tasks:
   - name: I need to execute a linux command
     command: hostname -f
     register: mycommandresult

   - name: I need to debug and view result of the above executed linux command
     debug:
       msg: "{{mycommandresult}}"
       
   - name: Installing git
     apt:
       name: git
       state: present
     when: mycommandresult.stderr==""

   - name: Installing tree
     apt:
       name: tree
       state: present
     when: mycommandresult.stderr!=""