---
- hosts: 172.31.38.27
  become: yes
  tasks:
   - include_tasks: filehandling.yml
   - name: I need to install apache2
     apt:
       name: apache2
   - name: Copy index file
     copy:
       src: myIndexFile
       dest: /var/www/html/index.html