---
- hosts: 172.31.38.27
  become: yes
  tasks:
   - include_tasks: filehandling.yml

   - name: I need to install apache2
     apt:
       name: apache2

   - name: Copy index file from master to node
     copy:
       src: myIndexFile
       dest: /var/www/html/index.html

   - name: I need to download a file from internet
     get_url:
       url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
       dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
       force_basic_auth: yes

   - name: Need to copy a dynamic file into node server
     template:
       src: myindexfile1.j2
       dest:  /var/www/html/index.html