---
- hosts: mywebservers
  become: yes
  tasks:
  - name: installing java on ubuntu
    apt:
      name: "{{myjavapackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
    
  - name: installing java on redhat
    ansible.builtin.dnf:
      name: "{{myjavapackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"