---
- hosts: all
  become: yes
  tasks:
  - name: apache2 will be installed
    apt:
      name: apache2
      state: present
  - name: apache2 will be started
    service:
      name: apache2
      state: started