---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: apache2 will be installed
    apt:
      name: apache2
      state: present
    when: ansible_os_family="Debian"

  - name: apache2 will be started
    service:
      name: apache2
      state: started
    when: ansible_os_family="Debian"

